import { test, expect } from "bun:test";
import { readFileSync } from "fs";
import { join } from "path";
import { decode, encode, type Envelope } from "./envelope";
import { subjects } from "./subjects";

// Golden fixtures are generated by the Go source of truth
// (internal/wire: `go test -run TestEnvelopeGolden -update`) and shared by all three SDKs.
const goldenDir = join(import.meta.dir, "../../../testdata/wire");
const golden = (name: string) => readFileSync(join(goldenDir, `${name}.json`));
const parse = (buf: Uint8Array) => JSON.parse(new TextDecoder().decode(buf));

// The same logical cases as goldenCases() in internal/wire/envelope_test.go. Constructing
// them through the typed Envelope shape means a renamed or retyped field fails to line up
// with the golden fixture.
const cases: Record<string, Envelope> = {
  call: { v: 1, id: "c-1", kind: "call", to: "counter", op: "get", payload: { n: 1 }, ts: 1700000000000 },
  cast: { v: 1, id: "c-2", kind: "cast", to: "counter", op: "inc", payload: {}, ts: 1700000000001 },
  reply_ok: { v: 1, id: "c-1", kind: "reply", status: "ok", payload: { value: 42 } },
  reply_error: {
    v: 1, id: "c-1", kind: "reply", status: "error",
    error: { type: "unknown_op", message: "unknown call op: nope", retryable: false },
  },
  hb: { v: 1, kind: "hb", to: "counter", ts: 1700000000002 },
  hb_metrics: {
    v: 1, kind: "hb", to: "counter",
    payload: { mailbox_depth: 2, mailbox_latency_ms: 1.5, processed_total: 10 },
    ts: 1700000000003,
  },
  ctl: { v: 1, kind: "ctl", op: "drain" },
  minimal: { v: 1, kind: "call" },
};

for (const [name, env] of Object.entries(cases)) {
  test(`encodes ${name} to the canonical wire form`, () => {
    // Field order differs from Go, so compare parsed values, not bytes.
    expect(parse(encode(env))).toEqual(parse(golden(name)));
  });

  test(`round-trips ${name} through decode/encode`, () => {
    const decoded = decode(golden(name));
    expect(parse(encode(decoded))).toEqual(parse(golden(name)));
  });
}

test("subject convention matches the contract", () => {
  const app = "demo", name = "counter";
  expect(subjects.call(app, name)).toBe("aether.demo.counter.call");
  expect(subjects.cast(app, name)).toBe("aether.demo.counter.cast");
  expect(subjects.info(app, name)).toBe("aether.demo.counter.info");
  expect(subjects.data(app, name)).toBe("aether.demo.counter.*");
  expect(subjects.stream(app, name)).toBe("aether_demo_counter");
  expect(subjects.ctl(name)).toBe("aether._lord.counter.ctl");
  expect(subjects.hb(name)).toBe("aether._lord.counter.hb");
  expect(subjects.lordCtl()).toBe("aether._lord.ctl");
  expect(subjects.events).toBe("aether._lord.events");
});
