"""Wire contract parity tests for the Python SDK.

The golden fixtures are generated by the Go source of truth
(internal/wire: `go test -run TestEnvelopeGolden -update`) and shared by all three SDKs.
These tests exercise only serialization and the subject helpers - no running NATS is needed
(the nats-py library is imported transitively by aether, but no broker is contacted).

Run: uv run --with nats-py -m unittest wire_parity_test   (from sdk/python)
"""

import json
import os
import unittest

import aether

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "testdata", "wire")


def golden(name):
    with open(os.path.join(GOLDEN_DIR, name + ".json"), "rb") as f:
        return f.read()


# The same logical cases as goldenCases() in internal/wire/envelope_test.go.
CASES = {
    "call": {"v": 1, "id": "c-1", "kind": "call", "to": "counter", "op": "get",
             "payload": {"n": 1}, "ts": 1700000000000},
    "call_traced": {"v": 1, "id": "c-9", "trace": "t-abc", "kind": "call", "to": "counter", "op": "get",
                    "payload": {"n": 1}, "ts": 1700000000004},
    "call_idem": {"v": 1, "id": "c-10", "idem": "withdraw-42", "kind": "call", "to": "account", "op": "withdraw",
                  "payload": {"amt": 5}, "ts": 1700000000005},
    "cast": {"v": 1, "id": "c-2", "kind": "cast", "to": "counter", "op": "inc",
             "payload": {}, "ts": 1700000000001},
    "reply_ok": {"v": 1, "id": "c-1", "kind": "reply", "status": "ok",
                 "payload": {"value": 42}},
    "reply_error": {"v": 1, "id": "c-1", "kind": "reply", "status": "error",
                    "error": {"type": "unknown_op", "message": "unknown call op: nope",
                              "retryable": False}},
    "hb": {"v": 1, "kind": "hb", "to": "counter", "ts": 1700000000002},
    "hb_metrics": {"v": 1, "kind": "hb", "to": "counter",
                   "payload": {"mailbox_depth": 2, "mailbox_latency_ms": 1.5, "processed_total": 10},
                   "ts": 1700000000003},
    "hb_describe": {"v": 1, "kind": "hb", "to": "counter",
                    "payload": {"mailbox_depth": 0, "mailbox_latency_ms": 0, "processed_total": 3,
                                "describe": {"call_ops": ["get", "value"], "cast_ops": ["inc", "reset"],
                                             "version": "1.2.0", "last_error": "handler_error: boom",
                                             "last_error_ms": 1700000000005}},
                    "ts": 1700000000006},
    "ctl": {"v": 1, "kind": "ctl", "op": "drain"},
    "minimal": {"v": 1, "kind": "call"},
}


class WireParity(unittest.TestCase):
    def test_encode_matches_golden(self):
        # Field order and whitespace differ from Go, so compare parsed values, not bytes.
        for name, case in CASES.items():
            with self.subTest(case=name):
                self.assertEqual(json.loads(aether._encode(case)), json.loads(golden(name)))

    def test_round_trip(self):
        for name in CASES:
            with self.subTest(case=name):
                decoded = aether._decode(golden(name))
                self.assertEqual(json.loads(aether._encode(decoded)), json.loads(golden(name)))

    def test_describe_dict_omits_empty_fields(self):
        # Empty fields are dropped to match the Go omitempty wire form.
        self.assertEqual(aether._describe_dict([], [], ""), {})
        self.assertEqual(aether._describe_dict(["get"], [], "1.0.0"),
                         {"call_ops": ["get"], "version": "1.0.0"})
        self.assertEqual(
            aether._describe_dict(["get"], ["inc"], "1.0.0", {"msg": "handler_error: boom", "ms": 42}),
            {"call_ops": ["get"], "cast_ops": ["inc"], "version": "1.0.0",
             "last_error": "handler_error: boom", "last_error_ms": 42})

    def test_fsm_describe(self):
        # Mirrors the Go TestFSMDescribe: the union of reaction ops as call and cast, plus _state.
        def _fn(ev, data, ctx):
            return aether.Outcome(data=data)
        defn = aether.FSM(
            name="gate", initial="idle", init=lambda ctx: 0, version="2.0.0",
            states={
                "idle": aether.State(on={"start": aether.Reaction(fn=_fn)}),
                "running": aether.State(on={"stop": aether.Reaction(fn=_fn), "start": aether.Reaction(fn=_fn)}),
            })
        d = aether._fsm_describe(defn)
        self.assertEqual(d["call_ops"], ["_state", "start", "stop"])
        self.assertEqual(d["cast_ops"], ["start", "stop"])
        self.assertEqual(d["version"], "2.0.0")

    def test_subjects(self):
        app, name = "demo", "counter"
        self.assertEqual(aether._sub_call(app, name), "aether.demo.counter.call")
        self.assertEqual(aether._sub_cast(app, name), "aether.demo.counter.cast")
        self.assertEqual(aether._sub_info(app, name), "aether.demo.counter.info")
        self.assertEqual(aether._sub_data(app, name), "aether.demo.counter.*")
        self.assertEqual(aether._stream(app, name), "aether_demo_counter")
        self.assertEqual(aether._sub_evt(app, name), "aether.demo.counter.evt")
        self.assertEqual(aether._stream_evt(app, name), "aether_demo_counter_evt")
        self.assertEqual(aether._sub_ctl(name), "aether._lord.counter.ctl")
        self.assertEqual(aether._sub_hb(name), "aether._lord.counter.hb")
        self.assertEqual(aether._sub_lord_ctl(), "aether._lord.ctl")


if __name__ == "__main__":
    unittest.main()
