"""Wire contract parity tests for the Python SDK.

The golden fixtures are generated by the Go source of truth
(internal/wire: `go test -run TestEnvelopeGolden -update`) and shared by all three SDKs.
These tests exercise only serialization and the subject helpers - no running NATS is needed
(the nats-py library is imported transitively by aether, but no broker is contacted).

Run: uv run --with nats-py -m unittest wire_parity_test   (from sdk/python)
"""

import json
import os
import unittest

import aether

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "testdata", "wire")


def golden(name):
    with open(os.path.join(GOLDEN_DIR, name + ".json"), "rb") as f:
        return f.read()


# The same logical cases as goldenCases() in internal/wire/envelope_test.go.
CASES = {
    "call": {"v": 1, "id": "c-1", "kind": "call", "to": "counter", "op": "get",
             "payload": {"n": 1}, "ts": 1700000000000},
    "cast": {"v": 1, "id": "c-2", "kind": "cast", "to": "counter", "op": "inc",
             "payload": {}, "ts": 1700000000001},
    "reply_ok": {"v": 1, "id": "c-1", "kind": "reply", "status": "ok",
                 "payload": {"value": 42}},
    "reply_error": {"v": 1, "id": "c-1", "kind": "reply", "status": "error",
                    "error": {"type": "unknown_op", "message": "unknown call op: nope",
                              "retryable": False}},
    "hb": {"v": 1, "kind": "hb", "to": "counter", "ts": 1700000000002},
    "ctl": {"v": 1, "kind": "ctl", "op": "drain"},
    "minimal": {"v": 1, "kind": "call"},
}


class WireParity(unittest.TestCase):
    def test_encode_matches_golden(self):
        # Field order and whitespace differ from Go, so compare parsed values, not bytes.
        for name, case in CASES.items():
            with self.subTest(case=name):
                self.assertEqual(json.loads(aether._encode(case)), json.loads(golden(name)))

    def test_round_trip(self):
        for name in CASES:
            with self.subTest(case=name):
                decoded = aether._decode(golden(name))
                self.assertEqual(json.loads(aether._encode(decoded)), json.loads(golden(name)))

    def test_subjects(self):
        app, name = "demo", "counter"
        self.assertEqual(aether._sub_call(app, name), "aether.demo.counter.call")
        self.assertEqual(aether._sub_cast(app, name), "aether.demo.counter.cast")
        self.assertEqual(aether._sub_info(app, name), "aether.demo.counter.info")
        self.assertEqual(aether._sub_data(app, name), "aether.demo.counter.*")
        self.assertEqual(aether._stream(app, name), "aether_demo_counter")
        self.assertEqual(aether._sub_ctl(name), "aether._lord.counter.ctl")
        self.assertEqual(aether._sub_hb(name), "aether._lord.counter.hb")
        self.assertEqual(aether._sub_lord_ctl(), "aether._lord.ctl")


if __name__ == "__main__":
    unittest.main()
